version: '3'
services:
  cte_federated_trainer:
    image: deltaml/federated-aggregator:latest
    ports:
       - "8080:8080"
    networks:
      - backend
  cte_data_owner:
    image: deltaml/model-buyer:latest
    ports:
     - "5000:5000"
    networks:
      - backend
    depends_on:
      - cte_federated_trainer
  cte_model_buyer:
    image: deltaml/model-buyer:latest
    ports:
     - "9090:9090"
    networks:
      - backend
    volumes:
    - ./db_dir:/app/db
networks:
  backend:
